version: "3.5"

services:
  fossa:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
      - BUILDKITE_BRANCH
      - FOSSA_API_KEY
    volumes:
      - ../:/go/src/go.temporal.io/sdk
